### Listar de livros
GET https://localhost:7220/api/livro/listar

### Buscar produtos
GET https://localhost:7220/api/livro/buscar/2

### Cadastrar produto
POST https://localhost:7220/api/livro/cadastrar
Content-Type: application/json

{
    "titulo" : "Agape",
    "descricao" : "uma amor verdadeiro",
    "quantidade" : 100,
    "preco" : 21.50,
    "generoId" : 4
}